export const iconsByFileExtension: Record<
  string,
  { icon: string; color: string; cterm_color: string; name: string }
> = {
  "3gp": { icon: "", color: "#FD971F", cterm_color: "208", name: "3gp" },
  "3mf": {
    icon: "󰆧",
    color: "#888888",
    cterm_color: "102",
    name: "3DObjectFile",
  },
  "7z": { icon: "", color: "#ECA517", cterm_color: "214", name: "7z" },
  Dockerfile: {
    icon: "󰡨",
    color: "#458EE6",
    cterm_color: "68",
    name: "Dockerfile",
  },
  R: { icon: "󰟔", color: "#2266BA", cterm_color: "25", name: "R" },
  a: {
    icon: "",
    color: "#DCDDD6",
    cterm_color: "253",
    name: "StaticLibraryArchive",
  },
  aac: {
    icon: "",
    color: "#00AFFF",
    cterm_color: "39",
    name: "AdvancedAudioCoding",
  },
  ada: { icon: "", color: "#599EFF", cterm_color: "111", name: "AdaFile" },
  adb: { icon: "", color: "#599EFF", cterm_color: "111", name: "AdaBody" },
  ads: {
    icon: "",
    color: "#A074C4",
    cterm_color: "140",
    name: "AdaSpecification",
  },
  ai: { icon: "", color: "#CBCB41", cterm_color: "185", name: "Ai" },
  aif: {
    icon: "",
    color: "#00AFFF",
    cterm_color: "39",
    name: "AudioInterchangeFileFormat",
  },
  aiff: {
    icon: "",
    color: "#00AFFF",
    cterm_color: "39",
    name: "AudioInterchangeFileFormat",
  },
  android: { icon: "", color: "#34A853", cterm_color: "35", name: "Android" },
  ape: { icon: "", color: "#00AFFF", cterm_color: "39", name: "MonkeysAudio" },
  apk: { icon: "", color: "#34A853", cterm_color: "35", name: "apk" },
  apl: { icon: "", color: "#24A148", cterm_color: "35", name: "APL" },
  app: { icon: "", color: "#9F0500", cterm_color: "124", name: "App" },
  applescript: {
    icon: "",
    color: "#6D8085",
    cterm_color: "66",
    name: "AppleScript",
  },
  asc: { icon: "󰦝", color: "#576D7F", cterm_color: "242", name: "Asc" },
  asm: { icon: "", color: "#0091BD", cterm_color: "31", name: "ASM" },
  ass: { icon: "󰨖", color: "#FFB713", cterm_color: "214", name: "Ass" },
  astro: { icon: "", color: "#E23F67", cterm_color: "197", name: "Astro" },
  avif: { icon: "", color: "#A074C4", cterm_color: "140", name: "Avif" },
  awk: { icon: "", color: "#4D5A5E", cterm_color: "240", name: "Awk" },
  azcli: { icon: "", color: "#0078D4", cterm_color: "32", name: "AzureCli" },
  bak: { icon: "󰁯", color: "#6D8086", cterm_color: "66", name: "Backup" },
  bash: { icon: "", color: "#89E051", cterm_color: "113", name: "Bash" },
  bat: { icon: "", color: "#C1F12E", cterm_color: "191", name: "Bat" },
  bazel: { icon: "", color: "#89E051", cterm_color: "113", name: "Bazel" },
  bib: { icon: "󱉟", color: "#CBCB41", cterm_color: "185", name: "BibTeX" },
  bicep: { icon: "", color: "#519ABA", cterm_color: "74", name: "Bicep" },
  bicepparam: {
    icon: "",
    color: "#9F74B3",
    cterm_color: "133",
    name: "BicepParameters",
  },
  bin: { icon: "", color: "#9F0500", cterm_color: "124", name: "Bin" },
  "blade.php": {
    icon: "",
    color: "#F05340",
    cterm_color: "203",
    name: "Blade",
  },
  blend: { icon: "󰂫", color: "#EA7600", cterm_color: "208", name: "Blender" },
  blp: { icon: "󰺾", color: "#5796E2", cterm_color: "68", name: "Blueprint" },
  bmp: { icon: "", color: "#A074C4", cterm_color: "140", name: "Bmp" },
  bqn: { icon: "", color: "#24A148", cterm_color: "35", name: "APL" },
  brep: {
    icon: "󰻫",
    color: "#839463",
    cterm_color: "101",
    name: "BoundaryRepresentation",
  },
  bz: { icon: "", color: "#ECA517", cterm_color: "214", name: "Bz" },
  bz2: { icon: "", color: "#ECA517", cterm_color: "214", name: "Bz2" },
  bz3: { icon: "", color: "#ECA517", cterm_color: "214", name: "Bz3" },
  bzl: { icon: "", color: "#89E051", cterm_color: "113", name: "Bzl" },
  c: { icon: "", color: "#599EFF", cterm_color: "111", name: "C" },
  "c++": { icon: "", color: "#F34B7D", cterm_color: "204", name: "CPlusPlus" },
  cache: { icon: "", color: "#FFFFFF", cterm_color: "231", name: "Cache" },
  cast: { icon: "", color: "#FD971F", cterm_color: "208", name: "Asciinema" },
  cbl: { icon: "", color: "#005CA5", cterm_color: "25", name: "Cobol" },
  cc: { icon: "", color: "#F34B7D", cterm_color: "204", name: "CPlusPlus" },
  ccm: {
    icon: "",
    color: "#F34B7D",
    cterm_color: "204",
    name: "CPlusPlusModule",
  },
  cfg: {
    icon: "",
    color: "#6D8086",
    cterm_color: "66",
    name: "Configuration",
  },
  cjs: { icon: "", color: "#CBCB41", cterm_color: "185", name: "Cjs" },
  clj: { icon: "", color: "#8DC149", cterm_color: "113", name: "Clojure" },
  cljc: { icon: "", color: "#8DC149", cterm_color: "113", name: "ClojureC" },
  cljd: { icon: "", color: "#519ABA", cterm_color: "74", name: "ClojureDart" },
  cljs: { icon: "", color: "#519ABA", cterm_color: "74", name: "ClojureJS" },
  cmake: { icon: "", color: "#DCE3EB", cterm_color: "254", name: "CMake" },
  cob: { icon: "", color: "#005CA5", cterm_color: "25", name: "Cobol" },
  cobol: { icon: "", color: "#005CA5", cterm_color: "25", name: "Cobol" },
  coffee: { icon: "", color: "#CBCB41", cterm_color: "185", name: "Coffee" },
  conda: { icon: "", color: "#43B02A", cterm_color: "34", name: "Conda" },
  conf: { icon: "", color: "#6D8086", cterm_color: "66", name: "Conf" },
  "config.ru": {
    icon: "",
    color: "#701516",
    cterm_color: "52",
    name: "ConfigRu",
  },
  cow: { icon: "󰆚", color: "#965824", cterm_color: "130", name: "CowsayFile" },
  cp: { icon: "", color: "#519ABA", cterm_color: "74", name: "Cp" },
  cpp: { icon: "", color: "#519ABA", cterm_color: "74", name: "Cpp" },
  cppm: { icon: "", color: "#519ABA", cterm_color: "74", name: "Cppm" },
  cpy: { icon: "", color: "#005CA5", cterm_color: "25", name: "Cobol" },
  cr: { icon: "", color: "#C8C8C8", cterm_color: "251", name: "Crystal" },
  crdownload: {
    icon: "",
    color: "#44CDA8",
    cterm_color: "43",
    name: "Crdownload",
  },
  cs: { icon: "󰌛", color: "#596706", cterm_color: "58", name: "Cs" },
  csh: { icon: "", color: "#4D5A5E", cterm_color: "240", name: "Csh" },
  cshtml: { icon: "󱦗", color: "#512BD4", cterm_color: "56", name: "RazorPage" },
  cson: { icon: "", color: "#CBCB41", cterm_color: "185", name: "Cson" },
  csproj: {
    icon: "󰪮",
    color: "#512BD4",
    cterm_color: "56",
    name: "CSharpProject",
  },
  css: { icon: "", color: "#42A5F5", cterm_color: "75", name: "Css" },
  csv: { icon: "", color: "#89E051", cterm_color: "113", name: "Csv" },
  cts: { icon: "", color: "#519ABA", cterm_color: "74", name: "Cts" },
  cu: { icon: "", color: "#89E051", cterm_color: "113", name: "cuda" },
  cue: { icon: "󰲹", color: "#ED95AE", cterm_color: "211", name: "Cue" },
  cuh: { icon: "", color: "#A074C4", cterm_color: "140", name: "cudah" },
  cxx: { icon: "", color: "#519ABA", cterm_color: "74", name: "Cxx" },
  cxxm: { icon: "", color: "#519ABA", cterm_color: "74", name: "Cxxm" },
  d: { icon: "", color: "#B03931", cterm_color: "124", name: "D" },
  "d.ts": {
    icon: "",
    color: "#D59855",
    cterm_color: "172",
    name: "TypeScriptDeclaration",
  },
  dart: { icon: "", color: "#03589C", cterm_color: "25", name: "Dart" },
  db: { icon: "", color: "#DAD8D8", cterm_color: "188", name: "Db" },
  dconf: { icon: "", color: "#FFFFFF", cterm_color: "231", name: "Dconf" },
  desktop: {
    icon: "",
    color: "#563D7C",
    cterm_color: "54",
    name: "DesktopEntry",
  },
  diff: { icon: "", color: "#41535B", cterm_color: "239", name: "Diff" },
  dll: { icon: "", color: "#4D2C0B", cterm_color: "52", name: "Dll" },
  doc: { icon: "󰈬", color: "#185ABD", cterm_color: "26", name: "Doc" },
  dockerignore: {
    icon: "󰡨",
    color: "#458EE6",
    cterm_color: "68",
    name: "DockerIgnore",
  },
  docx: { icon: "󰈬", color: "#185ABD", cterm_color: "26", name: "Docx" },
  dot: { icon: "󱁉", color: "#30638E", cterm_color: "24", name: "Dot" },
  download: {
    icon: "",
    color: "#44CDA8",
    cterm_color: "43",
    name: "Download",
  },
  drl: { icon: "", color: "#FFAFAF", cterm_color: "217", name: "Drools" },
  dropbox: { icon: "", color: "#0061FE", cterm_color: "27", name: "Dropbox" },
  dump: { icon: "", color: "#DAD8D8", cterm_color: "188", name: "Dump" },
  dwg: { icon: "󰻫", color: "#839463", cterm_color: "101", name: "AutoCADDwg" },
  dxf: { icon: "󰻫", color: "#839463", cterm_color: "101", name: "AutoCADDxf" },
  ebook: { icon: "", color: "#EAB16D", cterm_color: "215", name: "Ebook" },
  ebuild: {
    icon: "",
    color: "#4C416E",
    cterm_color: "60",
    name: "GentooBuild",
  },
  edn: { icon: "", color: "#519ABA", cterm_color: "74", name: "Edn" },
  eex: { icon: "", color: "#A074C4", cterm_color: "140", name: "Eex" },
  ejs: { icon: "", color: "#CBCB41", cterm_color: "185", name: "Ejs" },
  el: { icon: "", color: "#8172BE", cterm_color: "97", name: "Elisp" },
  elc: { icon: "", color: "#8172BE", cterm_color: "97", name: "Elisp" },
  elf: { icon: "", color: "#9F0500", cterm_color: "124", name: "Elf" },
  elm: { icon: "", color: "#519ABA", cterm_color: "74", name: "Elm" },
  eln: { icon: "", color: "#8172BE", cterm_color: "97", name: "Elisp" },
  env: { icon: "", color: "#FAF743", cterm_color: "227", name: "Env" },
  eot: {
    icon: "",
    color: "#ECECEC",
    cterm_color: "255",
    name: "EmbeddedOpenTypeFont",
  },
  epp: { icon: "", color: "#FFA61A", cterm_color: "214", name: "Epp" },
  epub: { icon: "", color: "#EAB16D", cterm_color: "215", name: "Epub" },
  erb: { icon: "", color: "#701516", cterm_color: "52", name: "Erb" },
  erl: { icon: "", color: "#B83998", cterm_color: "163", name: "Erl" },
  ex: { icon: "", color: "#A074C4", cterm_color: "140", name: "Ex" },
  exe: { icon: "", color: "#9F0500", cterm_color: "124", name: "Exe" },
  exs: { icon: "", color: "#A074C4", cterm_color: "140", name: "Exs" },
  "f#": { icon: "", color: "#519ABA", cterm_color: "74", name: "Fsharp" },
  f3d: { icon: "󰻫", color: "#839463", cterm_color: "101", name: "Fusion360" },
  f90: { icon: "󱈚", color: "#734F96", cterm_color: "97", name: "Fortran" },
  fbx: {
    icon: "󰆧",
    color: "#888888",
    cterm_color: "102",
    name: "3DObjectFile",
  },
  fcbak: { icon: "", color: "#CB333B", cterm_color: "160", name: "FreeCAD" },
  fcmacro: { icon: "", color: "#CB333B", cterm_color: "160", name: "FreeCAD" },
  fcmat: { icon: "", color: "#CB333B", cterm_color: "160", name: "FreeCAD" },
  fcparam: { icon: "", color: "#CB333B", cterm_color: "160", name: "FreeCAD" },
  fcscript: {
    icon: "",
    color: "#CB333B",
    cterm_color: "160",
    name: "FreeCAD",
  },
  fcstd: { icon: "", color: "#CB333B", cterm_color: "160", name: "FreeCAD" },
  fcstd1: { icon: "", color: "#CB333B", cterm_color: "160", name: "FreeCAD" },
  fctb: { icon: "", color: "#CB333B", cterm_color: "160", name: "FreeCAD" },
  fctl: { icon: "", color: "#CB333B", cterm_color: "160", name: "FreeCAD" },
  fdmdownload: {
    icon: "",
    color: "#44CDA8",
    cterm_color: "43",
    name: "Fdmdownload",
  },
  feature: { icon: "", color: "#00A818", cterm_color: "34", name: "Feature" },
  fish: { icon: "", color: "#4D5A5E", cterm_color: "240", name: "Fish" },
  flac: {
    icon: "",
    color: "#0075AA",
    cterm_color: "24",
    name: "FreeLosslessAudioCodec",
  },
  flc: {
    icon: "",
    color: "#ECECEC",
    cterm_color: "255",
    name: "FIGletFontControl",
  },
  flf: {
    icon: "",
    color: "#ECECEC",
    cterm_color: "255",
    name: "FIGletFontFormat",
  },
  fnl: { icon: "", color: "#FFF3D7", cterm_color: "230", name: "Fennel" },
  fodg: {
    icon: "",
    color: "#FFFB57",
    cterm_color: "227",
    name: "LibreOfficeGraphics",
  },
  fodp: {
    icon: "",
    color: "#FE9C45",
    cterm_color: "215",
    name: "LibreOfficeImpress",
  },
  fods: {
    icon: "",
    color: "#78FC4E",
    cterm_color: "119",
    name: "LibreOfficeCalc",
  },
  fodt: {
    icon: "",
    color: "#2DCBFD",
    cterm_color: "81",
    name: "LibreOfficeWriter",
  },
  fs: { icon: "", color: "#519ABA", cterm_color: "74", name: "Fs" },
  fsi: { icon: "", color: "#519ABA", cterm_color: "74", name: "Fsi" },
  fsscript: {
    icon: "",
    color: "#519ABA",
    cterm_color: "74",
    name: "Fsscript",
  },
  fsx: { icon: "", color: "#519ABA", cterm_color: "74", name: "Fsx" },
  gcode: { icon: "󰐫", color: "#1471AD", cterm_color: "32", name: "GCode" },
  gd: { icon: "", color: "#6D8086", cterm_color: "66", name: "GDScript" },
  gemspec: { icon: "", color: "#701516", cterm_color: "52", name: "Gemspec" },
  gif: { icon: "", color: "#A074C4", cterm_color: "140", name: "Gif" },
  git: { icon: "", color: "#F14C28", cterm_color: "196", name: "GitLogo" },
  glb: { icon: "", color: "#FFB13B", cterm_color: "214", name: "BinaryGLTF" },
  gleam: { icon: "", color: "#FFAFF3", cterm_color: "219", name: "Gleam" },
  gnumakefile: {
    icon: "",
    color: "#6D8086",
    cterm_color: "66",
    name: "Makefile",
  },
  go: { icon: "", color: "#519ABA", cterm_color: "74", name: "Go" },
  godot: {
    icon: "",
    color: "#6D8086",
    cterm_color: "66",
    name: "GodotProject",
  },
  gpr: {
    icon: "",
    color: "#6D8086",
    cterm_color: "66",
    name: "GPRBuildProject",
  },
  gql: { icon: "", color: "#E535AB", cterm_color: "199", name: "GraphQL" },
  gradle: { icon: "", color: "#005F87", cterm_color: "24", name: "Gradle" },
  graphql: { icon: "", color: "#E535AB", cterm_color: "199", name: "GraphQL" },
  gresource: { icon: "", color: "#FFFFFF", cterm_color: "231", name: "GTK" },
  gv: { icon: "󱁉", color: "#30638E", cterm_color: "24", name: "Gv" },
  gz: { icon: "", color: "#ECA517", cterm_color: "214", name: "Gz" },
  h: { icon: "", color: "#A074C4", cterm_color: "140", name: "H" },
  haml: { icon: "", color: "#EAEAE1", cterm_color: "255", name: "Haml" },
  hbs: { icon: "", color: "#F0772B", cterm_color: "202", name: "Hbs" },
  heex: { icon: "", color: "#A074C4", cterm_color: "140", name: "Heex" },
  hex: { icon: "", color: "#2E63FF", cterm_color: "27", name: "Hexadecimal" },
  hh: { icon: "", color: "#A074C4", cterm_color: "140", name: "Hh" },
  hpp: { icon: "", color: "#A074C4", cterm_color: "140", name: "Hpp" },
  hrl: { icon: "", color: "#B83998", cterm_color: "163", name: "Hrl" },
  hs: { icon: "", color: "#A074C4", cterm_color: "140", name: "Hs" },
  htm: { icon: "", color: "#E34C26", cterm_color: "196", name: "Htm" },
  html: { icon: "", color: "#E44D26", cterm_color: "196", name: "Html" },
  http: { icon: "", color: "#008EC7", cterm_color: "31", name: "HTTP" },
  huff: { icon: "󰡘", color: "#4242C7", cterm_color: "56", name: "Huff" },
  hurl: { icon: "", color: "#FF0288", cterm_color: "198", name: "Hurl" },
  hx: { icon: "", color: "#EA8220", cterm_color: "208", name: "Haxe" },
  hxx: { icon: "", color: "#A074C4", cterm_color: "140", name: "Hxx" },
  ical: { icon: "", color: "#2B2E83", cterm_color: "18", name: "Ical" },
  icalendar: {
    icon: "",
    color: "#2B2E83",
    cterm_color: "18",
    name: "Icalendar",
  },
  ico: { icon: "", color: "#CBCB41", cterm_color: "185", name: "Ico" },
  ics: { icon: "", color: "#2B2E83", cterm_color: "18", name: "Ics" },
  ifb: { icon: "", color: "#2B2E83", cterm_color: "18", name: "Ifb" },
  ifc: { icon: "󰻫", color: "#839463", cterm_color: "101", name: "Ifc" },
  ige: { icon: "󰻫", color: "#839463", cterm_color: "101", name: "Ige" },
  iges: { icon: "󰻫", color: "#839463", cterm_color: "101", name: "Iges" },
  igs: { icon: "󰻫", color: "#839463", cterm_color: "101", name: "Igs" },
  image: { icon: "", color: "#D0BEC8", cterm_color: "181", name: "Image" },
  img: { icon: "", color: "#D0BEC8", cterm_color: "181", name: "Img" },
  import: {
    icon: "",
    color: "#ECECEC",
    cterm_color: "255",
    name: "ImportConfiguration",
  },
  info: { icon: "", color: "#FFFFCD", cterm_color: "230", name: "Info" },
  ini: { icon: "", color: "#6D8086", cterm_color: "66", name: "Ini" },
  ino: { icon: "", color: "#56B6C2", cterm_color: "73", name: "Arduino" },
  ipynb: { icon: "", color: "#F57D01", cterm_color: "208", name: "Notebook" },
  iso: { icon: "", color: "#D0BEC8", cterm_color: "181", name: "Iso" },
  ixx: { icon: "", color: "#519ABA", cterm_color: "74", name: "Ixx" },
  java: { icon: "", color: "#CC3E44", cterm_color: "167", name: "Java" },
  jl: { icon: "", color: "#A270BA", cterm_color: "133", name: "Jl" },
  jpeg: { icon: "", color: "#A074C4", cterm_color: "140", name: "Jpeg" },
  jpg: { icon: "", color: "#A074C4", cterm_color: "140", name: "Jpg" },
  js: { icon: "", color: "#CBCB41", cterm_color: "185", name: "Js" },
  json: { icon: "", color: "#CBCB41", cterm_color: "185", name: "Json" },
  json5: { icon: "", color: "#CBCB41", cterm_color: "185", name: "Json5" },
  jsonc: { icon: "", color: "#CBCB41", cterm_color: "185", name: "Jsonc" },
  jsx: { icon: "", color: "#20C2E3", cterm_color: "45", name: "Jsx" },
  jwmrc: { icon: "", color: "#0078CD", cterm_color: "32", name: "JWM" },
  jxl: { icon: "", color: "#A074C4", cterm_color: "140", name: "JpegXl" },
  kbx: { icon: "󰯄", color: "#737672", cterm_color: "243", name: "Kbx" },
  kdb: { icon: "", color: "#529B34", cterm_color: "71", name: "Kdb" },
  kdbx: { icon: "", color: "#529B34", cterm_color: "71", name: "Kdbx" },
  kdenlive: {
    icon: "",
    color: "#83B8F2",
    cterm_color: "110",
    name: "Kdenlive",
  },
  kdenlivetitle: {
    icon: "",
    color: "#83B8F2",
    cterm_color: "110",
    name: "Kdenlive",
  },
  kicad_dru: { icon: "", color: "#FFFFFF", cterm_color: "231", name: "KiCad" },
  kicad_mod: { icon: "", color: "#FFFFFF", cterm_color: "231", name: "KiCad" },
  kicad_pcb: { icon: "", color: "#FFFFFF", cterm_color: "231", name: "KiCad" },
  kicad_prl: { icon: "", color: "#FFFFFF", cterm_color: "231", name: "KiCad" },
  kicad_pro: { icon: "", color: "#FFFFFF", cterm_color: "231", name: "KiCad" },
  kicad_sch: { icon: "", color: "#FFFFFF", cterm_color: "231", name: "KiCad" },
  kicad_sym: { icon: "", color: "#FFFFFF", cterm_color: "231", name: "KiCad" },
  kicad_wks: { icon: "", color: "#FFFFFF", cterm_color: "231", name: "KiCad" },
  ko: {
    icon: "",
    color: "#DCDDD6",
    cterm_color: "253",
    name: "LinuxKernelObject",
  },
  kpp: { icon: "", color: "#F245FB", cterm_color: "201", name: "Krita" },
  kra: { icon: "", color: "#F245FB", cterm_color: "201", name: "Krita" },
  krz: { icon: "", color: "#F245FB", cterm_color: "201", name: "Krita" },
  ksh: { icon: "", color: "#4D5A5E", cterm_color: "240", name: "Ksh" },
  kt: { icon: "", color: "#7F52FF", cterm_color: "99", name: "Kotlin" },
  kts: { icon: "", color: "#7F52FF", cterm_color: "99", name: "KotlinScript" },
  lck: { icon: "", color: "#BBBBBB", cterm_color: "250", name: "Lock" },
  leex: { icon: "", color: "#A074C4", cterm_color: "140", name: "Leex" },
  less: { icon: "", color: "#563D7C", cterm_color: "54", name: "Less" },
  lff: {
    icon: "",
    color: "#ECECEC",
    cterm_color: "255",
    name: "LibrecadFontFile",
  },
  lhs: { icon: "", color: "#A074C4", cterm_color: "140", name: "Lhs" },
  lib: { icon: "", color: "#4D2C0B", cterm_color: "52", name: "Lib" },
  license: { icon: "", color: "#CBCB41", cterm_color: "185", name: "License" },
  liquid: { icon: "", color: "#95BF47", cterm_color: "106", name: "Liquid" },
  lock: { icon: "", color: "#BBBBBB", cterm_color: "250", name: "Lock" },
  log: { icon: "󰌱", color: "#DDDDDD", cterm_color: "253", name: "Log" },
  lrc: { icon: "󰨖", color: "#FFB713", cterm_color: "214", name: "Lrc" },
  lua: { icon: "", color: "#51A0CF", cterm_color: "74", name: "Lua" },
  luac: { icon: "", color: "#51A0CF", cterm_color: "74", name: "Lua" },
  luau: { icon: "", color: "#00A2FF", cterm_color: "75", name: "Luau" },
  m: { icon: "", color: "#599EFF", cterm_color: "111", name: "ObjectiveC" },
  m3u: { icon: "󰲹", color: "#ED95AE", cterm_color: "211", name: "M3u" },
  m3u8: { icon: "󰲹", color: "#ED95AE", cterm_color: "211", name: "M3u8" },
  m4a: { icon: "", color: "#00AFFF", cterm_color: "39", name: "MPEG4" },
  m4v: { icon: "", color: "#FD971F", cterm_color: "208", name: "M4V" },
  magnet: { icon: "", color: "#A51B16", cterm_color: "124", name: "Magnet" },
  makefile: {
    icon: "",
    color: "#6D8086",
    cterm_color: "66",
    name: "Makefile",
  },
  markdown: {
    icon: "",
    color: "#DDDDDD",
    cterm_color: "253",
    name: "Markdown",
  },
  material: {
    icon: "",
    color: "#B83998",
    cterm_color: "163",
    name: "Material",
  },
  md: { icon: "", color: "#DDDDDD", cterm_color: "253", name: "Md" },
  md5: { icon: "󰕥", color: "#8C86AF", cterm_color: "103", name: "Md5" },
  mdx: { icon: "", color: "#519ABA", cterm_color: "74", name: "Mdx" },
  mint: { icon: "󰌪", color: "#87C095", cterm_color: "108", name: "Mint" },
  mjs: { icon: "", color: "#F1E05A", cterm_color: "185", name: "Mjs" },
  mk: { icon: "", color: "#6D8086", cterm_color: "66", name: "Makefile" },
  mkv: { icon: "", color: "#FD971F", cterm_color: "208", name: "Mkv" },
  ml: { icon: "", color: "#E37933", cterm_color: "166", name: "Ml" },
  mli: { icon: "", color: "#E37933", cterm_color: "166", name: "Mli" },
  mm: {
    icon: "",
    color: "#519ABA",
    cterm_color: "74",
    name: "ObjectiveCPlusPlus",
  },
  mo: { icon: "", color: "#9772FB", cterm_color: "135", name: "Motoko" },
  mobi: { icon: "", color: "#EAB16D", cterm_color: "215", name: "Mobi" },
  mojo: { icon: "", color: "#FF4C1F", cterm_color: "196", name: "Mojo" },
  mov: { icon: "", color: "#FD971F", cterm_color: "208", name: "MOV" },
  mp3: {
    icon: "",
    color: "#00AFFF",
    cterm_color: "39",
    name: "MPEGAudioLayerIII",
  },
  mp4: { icon: "", color: "#FD971F", cterm_color: "208", name: "Mp4" },
  mpp: { icon: "", color: "#519ABA", cterm_color: "74", name: "Mpp" },
  msf: { icon: "", color: "#137BE1", cterm_color: "33", name: "Thunderbird" },
  mts: { icon: "", color: "#519ABA", cterm_color: "74", name: "Mts" },
  mustache: {
    icon: "",
    color: "#E37933",
    cterm_color: "166",
    name: "Mustache",
  },
  nfo: { icon: "", color: "#FFFFCD", cterm_color: "230", name: "Nfo" },
  nim: { icon: "", color: "#F3D400", cterm_color: "220", name: "Nim" },
  nix: { icon: "", color: "#7EBAE4", cterm_color: "110", name: "Nix" },
  norg: { icon: "", color: "#4878BE", cterm_color: "32", name: "Norg" },
  nswag: { icon: "", color: "#85EA2D", cterm_color: "112", name: "Nswag" },
  nu: { icon: "", color: "#3AA675", cterm_color: "36", name: "Nushell" },
  o: { icon: "", color: "#9F0500", cterm_color: "124", name: "ObjectFile" },
  obj: {
    icon: "󰆧",
    color: "#888888",
    cterm_color: "102",
    name: "3DObjectFile",
  },
  odf: {
    icon: "",
    color: "#FF5A96",
    cterm_color: "204",
    name: "LibreOfficeFormula",
  },
  odg: {
    icon: "",
    color: "#FFFB57",
    cterm_color: "227",
    name: "LibreOfficeGraphics",
  },
  odin: { icon: "󰟢", color: "#3882D2", cterm_color: "32", name: "Odin" },
  odp: {
    icon: "",
    color: "#FE9C45",
    cterm_color: "215",
    name: "LibreOfficeImpress",
  },
  ods: {
    icon: "",
    color: "#78FC4E",
    cterm_color: "119",
    name: "LibreOfficeCalc",
  },
  odt: {
    icon: "",
    color: "#2DCBFD",
    cterm_color: "81",
    name: "LibreOfficeWriter",
  },
  oga: { icon: "", color: "#0075AA", cterm_color: "24", name: "OggVorbis" },
  ogg: { icon: "", color: "#0075AA", cterm_color: "24", name: "OggVorbis" },
  ogv: { icon: "", color: "#FD971F", cterm_color: "208", name: "OggVideo" },
  ogx: {
    icon: "",
    color: "#FD971F",
    cterm_color: "208",
    name: "OggMultiplex",
  },
  opus: {
    icon: "",
    color: "#0075AA",
    cterm_color: "24",
    name: "OpusAudioFile",
  },
  org: { icon: "", color: "#77AA99", cterm_color: "73", name: "OrgMode" },
  otf: {
    icon: "",
    color: "#ECECEC",
    cterm_color: "255",
    name: "OpenTypeFont",
  },
  out: { icon: "", color: "#9F0500", cterm_color: "124", name: "Out" },
  part: { icon: "", color: "#44CDA8", cterm_color: "43", name: "Part" },
  patch: { icon: "", color: "#41535B", cterm_color: "239", name: "Patch" },
  pck: {
    icon: "",
    color: "#6D8086",
    cterm_color: "66",
    name: "PackedResource",
  },
  pcm: {
    icon: "",
    color: "#0075AA",
    cterm_color: "24",
    name: "PulseCodeModulation",
  },
  pdf: { icon: "", color: "#B30B00", cterm_color: "124", name: "Pdf" },
  php: { icon: "", color: "#A074C4", cterm_color: "140", name: "Php" },
  pl: { icon: "", color: "#519ABA", cterm_color: "74", name: "Pl" },
  pls: { icon: "󰲹", color: "#ED95AE", cterm_color: "211", name: "Pls" },
  ply: {
    icon: "󰆧",
    color: "#888888",
    cterm_color: "102",
    name: "3DObjectFile",
  },
  pm: { icon: "", color: "#519ABA", cterm_color: "74", name: "Pm" },
  png: { icon: "", color: "#A074C4", cterm_color: "140", name: "Png" },
  po: { icon: "", color: "#2596BE", cterm_color: "31", name: "Localization" },
  pot: { icon: "", color: "#2596BE", cterm_color: "31", name: "Localization" },
  pp: { icon: "", color: "#FFA61A", cterm_color: "214", name: "Pp" },
  ppt: { icon: "󰈧", color: "#CB4A32", cterm_color: "160", name: "Ppt" },
  pptx: { icon: "󰈧", color: "#CB4A32", cterm_color: "160", name: "Pptx" },
  prisma: { icon: "", color: "#5A67D8", cterm_color: "62", name: "Prisma" },
  pro: { icon: "", color: "#E4B854", cterm_color: "179", name: "Prolog" },
  ps1: { icon: "󰨊", color: "#4273CA", cterm_color: "68", name: "PsScriptfile" },
  psb: { icon: "", color: "#519ABA", cterm_color: "74", name: "Psb" },
  psd: { icon: "", color: "#519ABA", cterm_color: "74", name: "Psd" },
  psd1: {
    icon: "󰨊",
    color: "#6975C4",
    cterm_color: "68",
    name: "PsManifestfile",
  },
  psm1: {
    icon: "󰨊",
    color: "#6975C4",
    cterm_color: "68",
    name: "PsScriptModulefile",
  },
  pub: { icon: "󰷖", color: "#E3C58E", cterm_color: "222", name: "Pub" },
  pxd: { icon: "", color: "#5AA7E4", cterm_color: "39", name: "Pxd" },
  pxi: { icon: "", color: "#5AA7E4", cterm_color: "39", name: "Pxi" },
  py: { icon: "", color: "#FFBC03", cterm_color: "214", name: "Py" },
  pyc: { icon: "", color: "#FFE291", cterm_color: "222", name: "Pyc" },
  pyd: { icon: "", color: "#FFE291", cterm_color: "222", name: "Pyd" },
  pyi: { icon: "", color: "#FFBC03", cterm_color: "214", name: "Pyi" },
  pyo: { icon: "", color: "#FFE291", cterm_color: "222", name: "Pyo" },
  pyw: { icon: "", color: "#5AA7E4", cterm_color: "39", name: "Pyw" },
  pyx: { icon: "", color: "#5AA7E4", cterm_color: "39", name: "Pyx" },
  qm: { icon: "", color: "#2596BE", cterm_color: "31", name: "Localization" },
  qml: { icon: "", color: "#40CD52", cterm_color: "77", name: "Qt" },
  qrc: { icon: "", color: "#40CD52", cterm_color: "77", name: "Qt" },
  qss: { icon: "", color: "#40CD52", cterm_color: "77", name: "Qt" },
  query: { icon: "", color: "#90A850", cterm_color: "107", name: "Query" },
  r: { icon: "󰟔", color: "#2266BA", cterm_color: "25", name: "R" },
  rake: { icon: "", color: "#701516", cterm_color: "52", name: "Rake" },
  rar: { icon: "", color: "#ECA517", cterm_color: "214", name: "Rar" },
  razor: { icon: "󱦘", color: "#512BD4", cterm_color: "56", name: "RazorPage" },
  rb: { icon: "", color: "#701516", cterm_color: "52", name: "Rb" },
  res: { icon: "", color: "#CC3E44", cterm_color: "167", name: "ReScript" },
  resi: {
    icon: "",
    color: "#F55385",
    cterm_color: "204",
    name: "ReScriptInterface",
  },
  rlib: { icon: "", color: "#DEA584", cterm_color: "216", name: "Rlib" },
  rmd: { icon: "", color: "#519ABA", cterm_color: "74", name: "Rmd" },
  rproj: { icon: "󰗆", color: "#358A5B", cterm_color: "29", name: "Rproj" },
  rs: { icon: "", color: "#DEA584", cterm_color: "216", name: "Rs" },
  rss: { icon: "", color: "#FB9D3B", cterm_color: "215", name: "Rss" },
  s: { icon: "", color: "#0071C5", cterm_color: "25", name: "ASM" },
  sass: { icon: "", color: "#F55385", cterm_color: "204", name: "Sass" },
  sbt: { icon: "", color: "#CC3E44", cterm_color: "167", name: "sbt" },
  sc: { icon: "", color: "#CC3E44", cterm_color: "167", name: "ScalaScript" },
  scad: { icon: "", color: "#F9D72C", cterm_color: "220", name: "OpenSCAD" },
  scala: { icon: "", color: "#CC3E44", cterm_color: "167", name: "Scala" },
  scm: { icon: "󰘧", color: "#EEEEEE", cterm_color: "255", name: "Scheme" },
  scss: { icon: "", color: "#F55385", cterm_color: "204", name: "Scss" },
  sh: { icon: "", color: "#4D5A5E", cterm_color: "240", name: "Sh" },
  sha1: { icon: "󰕥", color: "#8C86AF", cterm_color: "103", name: "Sha1" },
  sha224: { icon: "󰕥", color: "#8C86AF", cterm_color: "103", name: "Sha224" },
  sha256: { icon: "󰕥", color: "#8C86AF", cterm_color: "103", name: "Sha256" },
  sha384: { icon: "󰕥", color: "#8C86AF", cterm_color: "103", name: "Sha384" },
  sha512: { icon: "󰕥", color: "#8C86AF", cterm_color: "103", name: "Sha512" },
  sig: { icon: "󰘧", color: "#E37933", cterm_color: "166", name: "Sig" },
  signature: {
    icon: "󰘧",
    color: "#E37933",
    cterm_color: "166",
    name: "Signature",
  },
  skp: { icon: "󰻫", color: "#839463", cterm_color: "101", name: "SketchUp" },
  sldasm: {
    icon: "󰻫",
    color: "#839463",
    cterm_color: "101",
    name: "SolidWorksAsm",
  },
  sldprt: {
    icon: "󰻫",
    color: "#839463",
    cterm_color: "101",
    name: "SolidWorksPrt",
  },
  slim: { icon: "", color: "#E34C26", cterm_color: "196", name: "Slim" },
  sln: { icon: "", color: "#854CC7", cterm_color: "98", name: "Sln" },
  slnx: { icon: "", color: "#854CC7", cterm_color: "98", name: "Slnx" },
  slvs: { icon: "󰻫", color: "#839463", cterm_color: "101", name: "SolveSpace" },
  sml: { icon: "󰘧", color: "#E37933", cterm_color: "166", name: "Sml" },
  so: { icon: "", color: "#DCDDD6", cterm_color: "253", name: "SharedObject" },
  sol: { icon: "", color: "#519ABA", cterm_color: "74", name: "Solidity" },
  "spec.js": {
    icon: "",
    color: "#CBCB41",
    cterm_color: "185",
    name: "SpecJs",
  },
  "spec.jsx": {
    icon: "",
    color: "#20C2E3",
    cterm_color: "45",
    name: "JavaScriptReactSpec",
  },
  "spec.ts": { icon: "", color: "#519ABA", cterm_color: "74", name: "SpecTs" },
  "spec.tsx": {
    icon: "",
    color: "#1354BF",
    cterm_color: "26",
    name: "TypeScriptReactSpec",
  },
  spx: {
    icon: "",
    color: "#0075AA",
    cterm_color: "24",
    name: "OggSpeexAudio",
  },
  sql: { icon: "", color: "#DAD8D8", cterm_color: "188", name: "Sql" },
  sqlite: { icon: "", color: "#DAD8D8", cterm_color: "188", name: "Sql" },
  sqlite3: { icon: "", color: "#DAD8D8", cterm_color: "188", name: "Sql" },
  srt: { icon: "󰨖", color: "#FFB713", cterm_color: "214", name: "Srt" },
  ssa: { icon: "󰨖", color: "#FFB713", cterm_color: "214", name: "Ssa" },
  ste: { icon: "󰻫", color: "#839463", cterm_color: "101", name: "Ste" },
  step: { icon: "󰻫", color: "#839463", cterm_color: "101", name: "Step" },
  stl: {
    icon: "󰆧",
    color: "#888888",
    cterm_color: "102",
    name: "3DObjectFile",
  },
  "stories.js": {
    icon: "",
    color: "#FF4785",
    cterm_color: "204",
    name: "StorybookJavaScript",
  },
  "stories.jsx": {
    icon: "",
    color: "#FF4785",
    cterm_color: "204",
    name: "StorybookJsx",
  },
  "stories.mjs": {
    icon: "",
    color: "#FF4785",
    cterm_color: "204",
    name: "StorybookMjs",
  },
  "stories.svelte": {
    icon: "",
    color: "#FF4785",
    cterm_color: "204",
    name: "StorybookSvelte",
  },
  "stories.ts": {
    icon: "",
    color: "#FF4785",
    cterm_color: "204",
    name: "StorybookTypeScript",
  },
  "stories.tsx": {
    icon: "",
    color: "#FF4785",
    cterm_color: "204",
    name: "StorybookTsx",
  },
  "stories.vue": {
    icon: "",
    color: "#FF4785",
    cterm_color: "204",
    name: "StorybookVue",
  },
  stp: { icon: "󰻫", color: "#839463", cterm_color: "101", name: "Stp" },
  strings: {
    icon: "",
    color: "#2596BE",
    cterm_color: "31",
    name: "Localization",
  },
  styl: { icon: "", color: "#8DC149", cterm_color: "113", name: "Styl" },
  sub: { icon: "󰨖", color: "#FFB713", cterm_color: "214", name: "Sub" },
  sublime: { icon: "", color: "#E37933", cterm_color: "166", name: "Sublime" },
  suo: { icon: "", color: "#854CC7", cterm_color: "98", name: "Suo" },
  sv: { icon: "󰍛", color: "#019833", cterm_color: "28", name: "SystemVerilog" },
  svelte: { icon: "", color: "#FF3E00", cterm_color: "196", name: "Svelte" },
  svg: { icon: "󰜡", color: "#FFB13B", cterm_color: "214", name: "Svg" },
  svh: {
    icon: "󰍛",
    color: "#019833",
    cterm_color: "28",
    name: "SystemVerilog",
  },
  swift: { icon: "", color: "#E37933", cterm_color: "166", name: "Swift" },
  t: { icon: "", color: "#519ABA", cterm_color: "74", name: "Tor" },
  tbc: { icon: "󰛓", color: "#1E5CB3", cterm_color: "25", name: "Tcl" },
  tcl: { icon: "󰛓", color: "#1E5CB3", cterm_color: "25", name: "Tcl" },
  templ: { icon: "", color: "#DBBD30", cterm_color: "178", name: "Templ" },
  terminal: {
    icon: "",
    color: "#31B53E",
    cterm_color: "34",
    name: "Terminal",
  },
  "test.js": {
    icon: "",
    color: "#CBCB41",
    cterm_color: "185",
    name: "TestJs",
  },
  "test.jsx": {
    icon: "",
    color: "#20C2E3",
    cterm_color: "45",
    name: "JavaScriptReactTest",
  },
  "test.ts": { icon: "", color: "#519ABA", cterm_color: "74", name: "TestTs" },
  "test.tsx": {
    icon: "",
    color: "#1354BF",
    cterm_color: "26",
    name: "TypeScriptReactTest",
  },
  tex: { icon: "", color: "#3D6117", cterm_color: "22", name: "Tex" },
  tf: { icon: "", color: "#5F43E9", cterm_color: "93", name: "Terraform" },
  tfvars: { icon: "", color: "#5F43E9", cterm_color: "93", name: "TFVars" },
  tgz: { icon: "", color: "#ECA517", cterm_color: "214", name: "Tgz" },
  tmux: { icon: "", color: "#14BA19", cterm_color: "34", name: "Tmux" },
  toml: { icon: "", color: "#9C4221", cterm_color: "124", name: "Toml" },
  torrent: { icon: "", color: "#44CDA8", cterm_color: "43", name: "Torrent" },
  tres: {
    icon: "",
    color: "#6D8086",
    cterm_color: "66",
    name: "GodotTextResource",
  },
  ts: { icon: "", color: "#519ABA", cterm_color: "74", name: "TypeScript" },
  tscn: {
    icon: "",
    color: "#6D8086",
    cterm_color: "66",
    name: "GodotTextScene",
  },
  tsconfig: {
    icon: "",
    color: "#FF8700",
    cterm_color: "208",
    name: "TypoScriptConfig",
  },
  tsx: { icon: "", color: "#1354BF", cterm_color: "26", name: "Tsx" },
  ttf: {
    icon: "",
    color: "#ECECEC",
    cterm_color: "255",
    name: "TrueTypeFont",
  },
  twig: { icon: "", color: "#8DC149", cterm_color: "113", name: "Twig" },
  txt: { icon: "󰈙", color: "#89E051", cterm_color: "113", name: "Txt" },
  txz: { icon: "", color: "#ECA517", cterm_color: "214", name: "Txz" },
  typ: { icon: "", color: "#0DBCC0", cterm_color: "37", name: "Typst" },
  typoscript: {
    icon: "",
    color: "#FF8700",
    cterm_color: "208",
    name: "TypoScript",
  },
  ui: { icon: "", color: "#015BF0", cterm_color: "27", name: "UI" },
  v: { icon: "󰍛", color: "#019833", cterm_color: "28", name: "Verilog" },
  vala: { icon: "", color: "#7B3DB9", cterm_color: "91", name: "Vala" },
  vh: { icon: "󰍛", color: "#019833", cterm_color: "28", name: "Verilog" },
  vhd: { icon: "󰍛", color: "#019833", cterm_color: "28", name: "VHDL" },
  vhdl: { icon: "󰍛", color: "#019833", cterm_color: "28", name: "VHDL" },
  vi: { icon: "", color: "#FEC60A", cterm_color: "220", name: "LabView" },
  vim: { icon: "", color: "#019833", cterm_color: "28", name: "Vim" },
  vsh: { icon: "", color: "#5D87BF", cterm_color: "67", name: "Vlang" },
  vsix: { icon: "", color: "#854CC7", cterm_color: "98", name: "Vsix" },
  vue: { icon: "", color: "#8DC149", cterm_color: "113", name: "Vue" },
  wasm: { icon: "", color: "#5C4CDB", cterm_color: "62", name: "Wasm" },
  wav: {
    icon: "",
    color: "#00AFFF",
    cterm_color: "39",
    name: "WaveformAudioFile",
  },
  webm: { icon: "", color: "#FD971F", cterm_color: "208", name: "Webm" },
  webmanifest: {
    icon: "",
    color: "#F1E05A",
    cterm_color: "185",
    name: "Webmanifest",
  },
  webp: { icon: "", color: "#A074C4", cterm_color: "140", name: "Webp" },
  webpack: { icon: "󰜫", color: "#519ABA", cterm_color: "74", name: "Webpack" },
  wma: {
    icon: "",
    color: "#00AFFF",
    cterm_color: "39",
    name: "WindowsMediaAudio",
  },
  woff: {
    icon: "",
    color: "#ECECEC",
    cterm_color: "255",
    name: "WebOpenFontFormat",
  },
  woff2: {
    icon: "",
    color: "#ECECEC",
    cterm_color: "255",
    name: "WebOpenFontFormat",
  },
  wrl: { icon: "󰆧", color: "#888888", cterm_color: "102", name: "VRML" },
  wrz: { icon: "󰆧", color: "#888888", cterm_color: "102", name: "VRML" },
  wv: { icon: "", color: "#00AFFF", cterm_color: "39", name: "WavPack" },
  wvc: {
    icon: "",
    color: "#00AFFF",
    cterm_color: "39",
    name: "WavPackCorrection",
  },
  x: { icon: "", color: "#599EFF", cterm_color: "111", name: "Logos" },
  xaml: { icon: "󰙳", color: "#512BD4", cterm_color: "56", name: "Xaml" },
  xcf: { icon: "", color: "#635B46", cterm_color: "240", name: "GIMP" },
  xcplayground: {
    icon: "",
    color: "#E37933",
    cterm_color: "166",
    name: "XcPlayground",
  },
  xcstrings: {
    icon: "",
    color: "#2596BE",
    cterm_color: "31",
    name: "XcLocalization",
  },
  xls: { icon: "󰈛", color: "#207245", cterm_color: "29", name: "Xls" },
  xlsx: { icon: "󰈛", color: "#207245", cterm_color: "29", name: "Xlsx" },
  xm: { icon: "", color: "#519ABA", cterm_color: "74", name: "Logos" },
  xml: { icon: "󰗀", color: "#E37933", cterm_color: "166", name: "Xml" },
  xpi: { icon: "", color: "#FF1B01", cterm_color: "196", name: "Xpi" },
  xul: { icon: "", color: "#E37933", cterm_color: "166", name: "Xul" },
  xz: { icon: "", color: "#ECA517", cterm_color: "214", name: "Xz" },
  yaml: { icon: "", color: "#6D8086", cterm_color: "66", name: "Yaml" },
  yml: { icon: "", color: "#6D8086", cterm_color: "66", name: "Yml" },
  zig: { icon: "", color: "#F69A1B", cterm_color: "172", name: "Zig" },
  zip: { icon: "", color: "#ECA517", cterm_color: "214", name: "Zip" },
  zsh: { icon: "", color: "#89E051", cterm_color: "113", name: "Zsh" },
  zst: { icon: "", color: "#ECA517", cterm_color: "214", name: "Zst" },
  "🔥": { icon: "", color: "#FF4C1F", cterm_color: "196", name: "Mojo" },
};
